-- Schema-only dump of the public schema (no data).
-- Generated by scripts/sync-supabase-schema.mjs on 2026-06-23T10:58:35.577Z

-- ============ Tables ============
CREATE TABLE public."company" (
  "id" text NOT NULL,
  "name" text NOT NULL,
  "link" text NOT NULL,
  "type" text NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE public."job" (
  "title" text NOT NULL,
  "location" text NOT NULL,
  "detail_link" text NOT NULL,
  "salary" text NOT NULL,
  "id" text NOT NULL,
  "description" text NOT NULL,
  "max_salary" integer NOT NULL,
  "min_salary" integer NOT NULL,
  "salary_type" text NOT NULL,
  "created_at" timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
  "updated_at" timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
  "company_id" text NOT NULL,
  "closed" boolean DEFAULT false NOT NULL,
  "salary_manual" boolean DEFAULT false NOT NULL
);
CREATE TABLE public."job_description_bin" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "content" text NOT NULL
);
CREATE TABLE public."job_keyword" (
  "id" text NOT NULL,
  "keywords" text[] NOT NULL,
  "description_ch_en_ratio" numeric NOT NULL
);
CREATE TABLE public."job_preference" (
  "job_id" text NOT NULL,
  "preference" text NOT NULL,
  "updated_at" timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
  "user_id" uuid NOT NULL
);
CREATE TABLE public."job_source" (
  "url" text NOT NULL
);
CREATE TABLE public."job_source_url" (
  "url" text NOT NULL,
  "page_index" bigint DEFAULT '1'::bigint NOT NULL,
  "status" text NOT NULL
);
CREATE TABLE public."job_tech" (
  "job_id" text NOT NULL,
  "tech" text NOT NULL,
  "keywords" text NOT NULL
);
CREATE TABLE public."keyword" (
  "id" text NOT NULL,
  "count" integer NOT NULL
);
CREATE TABLE public."keyword_bin" (
  "id" text NOT NULL
);
CREATE TABLE public."location_group" (
  "id" text NOT NULL
);
CREATE TABLE public."location_group_location" (
  "location_group" text NOT NULL,
  "location" text NOT NULL
);
CREATE TABLE public."tech" (
  "id" text NOT NULL,
  "category" text NOT NULL,
  "label" text NOT NULL,
  "tags" text[],
  "icon_slugs" text[]
);
CREATE TABLE public."tech_keyword" (
  "tech" text NOT NULL,
  "keyword" text NOT NULL
);
CREATE TABLE public."tech_parent" (
  "parent" text NOT NULL,
  "child" text NOT NULL
);

-- ============ Constraints ============
ALTER TABLE public."company" ADD CONSTRAINT "pk_company" PRIMARY KEY (id);
ALTER TABLE public."job" ADD CONSTRAINT "pk_job" PRIMARY KEY (id);
ALTER TABLE public."job" ADD CONSTRAINT "job_company_id_fkey" FOREIGN KEY (company_id) REFERENCES company(id) ON UPDATE CASCADE;
ALTER TABLE public."job_description_bin" ADD CONSTRAINT "job_description_bin_pkey" PRIMARY KEY (id);
ALTER TABLE public."job_keyword" ADD CONSTRAINT "pk_job_keyword" PRIMARY KEY (id);
ALTER TABLE public."job_keyword" ADD CONSTRAINT "job_keyword_id_fkey" FOREIGN KEY (id) REFERENCES job(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public."job_preference" ADD CONSTRAINT "pk_job_preference" PRIMARY KEY (job_id, user_id);
ALTER TABLE public."job_preference" ADD CONSTRAINT "job_preference_job_id_fkey" FOREIGN KEY (job_id) REFERENCES job(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public."job_preference" ADD CONSTRAINT "job_preference_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id);
ALTER TABLE public."job_source" ADD CONSTRAINT "job_source_pkey" PRIMARY KEY (url);
ALTER TABLE public."job_source_url" ADD CONSTRAINT "job_source_urls_pkey" PRIMARY KEY (url, page_index);
ALTER TABLE public."job_tech" ADD CONSTRAINT "pk_job_tech" PRIMARY KEY (job_id, tech);
ALTER TABLE public."job_tech" ADD CONSTRAINT "job_join_tech_job_id_fkey" FOREIGN KEY (job_id) REFERENCES job(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public."job_tech" ADD CONSTRAINT "job_join_tech_tech_fkey" FOREIGN KEY (tech) REFERENCES tech(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public."keyword" ADD CONSTRAINT "pk_keyword" PRIMARY KEY (id);
ALTER TABLE public."keyword_bin" ADD CONSTRAINT "pk_keyword_bin" PRIMARY KEY (id);
ALTER TABLE public."location_group" ADD CONSTRAINT "location_group_pkey" PRIMARY KEY (id);
ALTER TABLE public."location_group_location" ADD CONSTRAINT "location_group_location_pkey" PRIMARY KEY (location_group, location);
ALTER TABLE public."location_group_location" ADD CONSTRAINT "location_group_location_location_group_fkey" FOREIGN KEY (location_group) REFERENCES location_group(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public."tech" ADD CONSTRAINT "pk_tech" PRIMARY KEY (id);
ALTER TABLE public."tech_keyword" ADD CONSTRAINT "pk_tech_keyword" PRIMARY KEY (tech, keyword);
ALTER TABLE public."tech_keyword" ADD CONSTRAINT "tech_keyword_join_tech_fkey" FOREIGN KEY (tech) REFERENCES tech(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public."tech_keyword" ADD CONSTRAINT "tech_keyword_mapping_keyword_fkey" FOREIGN KEY (keyword) REFERENCES keyword(id);
ALTER TABLE public."tech_parent" ADD CONSTRAINT "tech_parent_pkey" PRIMARY KEY (parent, child);
ALTER TABLE public."tech_parent" ADD CONSTRAINT "tech_parent_child_fkey" FOREIGN KEY (child) REFERENCES tech(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public."tech_parent" ADD CONSTRAINT "tech_parent_parent_fkey" FOREIGN KEY (parent) REFERENCES tech(id) ON UPDATE CASCADE ON DELETE CASCADE;

-- ============ Indexes ============
CREATE INDEX ix_job_closed ON public.job USING btree (closed);
CREATE INDEX ix_job_closed_company_id ON public.job USING btree (closed, company_id);
CREATE INDEX ix_job_company_id ON public.job USING btree (company_id);
CREATE INDEX ix_job_min_salary_max_salary_updated_at ON public.job USING btree (min_salary DESC, max_salary DESC, updated_at DESC);
CREATE INDEX job_location_idx ON public.job USING btree (location);
CREATE INDEX job_salary_idx ON public.job USING btree (salary);
CREATE INDEX ix_job_preference_user_id ON public.job_preference USING btree (user_id);
CREATE INDEX ix_job_preference_user_id_job_id ON public.job_preference USING btree (user_id, job_id);
CREATE INDEX ix_job_tech_job_id ON public.job_tech USING btree (job_id);
CREATE INDEX ix_job_tech_tech ON public.job_tech USING btree (tech);
CREATE INDEX location_group_location_location_group_idx ON public.location_group_location USING btree (location_group);
CREATE INDEX location_group_location_location_idx ON public.location_group_location USING btree (location);
CREATE INDEX ix_mv_company_job_count ON public.mv_company USING btree (job_count);
CREATE INDEX ix_mv_company_type ON public.mv_company USING btree (company_type);
CREATE UNIQUE INDEX ux_mv_company_company_id ON public.mv_company USING btree (company_id);
CREATE INDEX ix_mv_job_company_id ON public.mv_job USING btree (company_id);
CREATE INDEX ix_mv_job_max_salary ON public.mv_job USING btree (max_salary DESC);
CREATE INDEX ix_mv_job_min_salary ON public.mv_job USING btree (min_salary DESC);
CREATE INDEX ix_mv_job_salary_type ON public.mv_job USING btree (salary_type);
CREATE INDEX ix_mv_job_techs ON public.mv_job USING gin (techs);
CREATE INDEX ix_mv_job_updated_at ON public.mv_job USING btree (updated_at DESC);
CREATE UNIQUE INDEX mv_job_id_idx ON public.mv_job USING btree (id);
CREATE INDEX mv_job_location_idx ON public.mv_job USING btree (location);
CREATE UNIQUE INDEX mv_location_group_idx ON public.mv_location_group USING btree (location);
CREATE UNIQUE INDEX idx_mv_salary_type_median_ratio_type ON public.mv_salary_type_median_ratio USING btree (salary_type);
CREATE UNIQUE INDEX idx_mv_salary_weighted_ratio_type ON public.mv_salary_weighted_ratio USING btree (salary_type);
CREATE INDEX ix_mv_tech_category ON public.mv_tech USING btree (category);
CREATE INDEX ix_mv_tech_count ON public.mv_tech USING btree (count DESC);
CREATE INDEX ix_mv_tech_keywords ON public.mv_tech USING gin (keywords);
CREATE UNIQUE INDEX ux_mv_tech_tech ON public.mv_tech USING btree (tech);
CREATE UNIQUE INDEX ux_mv_tech_category_category ON public.mv_tech_category USING btree (category);
CREATE UNIQUE INDEX ux_mv_tech_combo_stats_tech1_tech2 ON public.mv_tech_combo_stats USING btree (tech1, tech2);
CREATE UNIQUE INDEX ux_mv_tech_ranking_tech ON public.mv_tech_ranking USING btree (tech);
CREATE UNIQUE INDEX ux_mv_tech_tags ON public.mv_tech_tags USING btree (tag, category);
CREATE INDEX tech_category_idx ON public.tech USING btree (category);
CREATE INDEX ix_tech_keyword_keyword ON public.tech_keyword USING btree (keyword);
CREATE INDEX ix_tech_keyword_tech ON public.tech_keyword USING btree (tech);
CREATE INDEX tech_parent_child_idx ON public.tech_parent USING btree (child);
CREATE INDEX tech_parent_parent_idx ON public.tech_parent USING btree (parent);

-- ============ Views ============
CREATE MATERIALIZED VIEW public."mv_company" AS
 SELECT COALESCE(c.id, ''::text) AS company_id,
    COALESCE(c.name, ''::text) AS company_name,
    COALESCE(c.link, ''::text) AS company_link,
    COALESCE(c.type, ''::text) AS company_type,
    COALESCE(count(DISTINCT j.id), 0::bigint) AS job_count,
    COALESCE(array_agg(DISTINCT jkg.tech), '{}'::text[]) AS techs
   FROM company c
     JOIN job j ON j.company_id = c.id
     JOIN job_tech jkg ON jkg.job_id = j.id
  WHERE j.closed = false
  GROUP BY c.id, c.name, c.link, c.type
 HAVING count(DISTINCT j.id) > 0;

CREATE MATERIALIZED VIEW public."mv_job" AS
 SELECT j.id,
    j.title,
    COALESCE(lg.id, j.location) AS location,
    j.detail_link,
    j.salary,
    j.salary_type,
    j.min_salary,
    j.max_salary,
        CASE
            WHEN j.min_salary > 0 AND j.max_salary < 9999999 THEN round((j.min_salary + j.max_salary)::numeric / 2.0, 0)
            WHEN j.min_salary > 0 AND j.max_salary = 9999999 THEN round(j.min_salary::numeric * (1.0 + mv.ratio) / 2.0, 0)
            ELSE NULL::numeric
        END AS avg_salary,
    j.created_at,
    j.updated_at,
    j.description,
    c.id AS company_id,
    c.name AS company_name,
    c.link AS company_link,
    c.type AS company_type,
    array_agg(jkg.tech) FILTER (WHERE jkg.tech IS NOT NULL) AS techs,
    array_agg((jkg.tech || ':'::text) || jkg.keywords) FILTER (WHERE jkg.tech IS NOT NULL) AS tech_mappings,
    j.closed,
    jk.description_ch_en_ratio
   FROM job j
     JOIN job_keyword jk ON jk.id = j.id
     JOIN company c ON j.company_id = c.id
     LEFT JOIN job_tech jkg ON jkg.job_id = j.id
     LEFT JOIN location_group_location lgl ON j.location = lgl.location
     LEFT JOIN location_group lg ON lgl.location_group = lg.id
     LEFT JOIN mv_salary_weighted_ratio mv ON j.salary_type = mv.salary_type
  WHERE j.closed = false
  GROUP BY j.id, j.title, (COALESCE(lg.id, j.location)), j.detail_link, j.salary, j.salary_type, j.min_salary, j.max_salary, j.created_at, j.updated_at, j.description, c.id, c.name, c.link, c.type, jk.description_ch_en_ratio, j.closed, mv.ratio
  ORDER BY j.min_salary DESC, j.max_salary DESC, j.updated_at DESC;

CREATE MATERIALIZED VIEW public."mv_location_group" AS
 SELECT lg.id AS location,
    count(*) AS count
   FROM job j
     LEFT JOIN location_group_location lgl ON lgl.location = j.location
     LEFT JOIN location_group lg ON lg.id = lgl.location_group
  WHERE lg.id IS NOT NULL AND j.closed = false
  GROUP BY lg.id;

CREATE MATERIALIZED VIEW public."mv_salary_type_median_ratio" AS
 WITH job_salary AS (
         SELECT j.salary_type,
                CASE
                    WHEN j.min_salary > 0 AND j.max_salary < 9999999 AND j.max_salary >= j.min_salary THEN (j.min_salary + j.max_salary)::numeric / 2.0
                    WHEN j.min_salary > 0 AND j.max_salary = 9999999 THEN j.min_salary::numeric * (1.0 + mv.ratio) / 2.0
                    ELSE NULL::numeric
                END::double precision AS representative_salary
           FROM job j
             JOIN mv_salary_weighted_ratio mv ON j.salary_type = mv.salary_type
          WHERE (j.salary_type = ANY (ARRAY['month'::text, 'year'::text])) AND j.closed = false
        )
 SELECT salary_type,
    round(percentile_cont(0.50::double precision) WITHIN GROUP (ORDER BY representative_salary)::numeric, 0) AS median_mark,
    round(percentile_cont(0.75::double precision) WITHIN GROUP (ORDER BY representative_salary)::numeric, 0) AS high_mark,
    round(percentile_cont(0.88::double precision) WITHIN GROUP (ORDER BY representative_salary)::numeric, 0) AS top_mark
   FROM job_salary
  WHERE representative_salary IS NOT NULL
  GROUP BY salary_type
  ORDER BY salary_type;

CREATE MATERIALIZED VIEW public."mv_salary_weighted_ratio" AS
 SELECT salary_type,
    round(avg(max_salary::numeric / min_salary::numeric), 2) AS ratio
   FROM job
  WHERE min_salary > 0 AND max_salary < 9999999 AND max_salary >= min_salary AND (salary_type = ANY (ARRAY['month'::text, 'year'::text]))
  GROUP BY salary_type;

CREATE MATERIALIZED VIEW public."mv_tech" AS
 WITH keyword_base AS (
         SELECT k.id AS keyword_id,
            k.count,
            kgkm.tech AS keyword_group
           FROM keyword k
             LEFT JOIN keyword_bin kb ON k.id = kb.id
             LEFT JOIN tech_keyword kgkm ON k.id = kgkm.keyword
          WHERE kb.id IS NULL
        ), aggregated_groups AS (
         SELECT COALESCE(kb.keyword_group, kb.keyword_id) AS group_id,
            sum(kb.count) AS total_count,
            array_agg(kb.keyword_id) AS keywords
           FROM keyword_base kb
          GROUP BY (COALESCE(kb.keyword_group, kb.keyword_id))
         HAVING sum(kb.count) > 2
        )
 SELECT ag.group_id AS tech,
    COALESCE(max(kg.label), ag.group_id) AS label,
    ag.total_count AS count,
    ag.keywords,
    kg.category,
    ( SELECT array_agg(DISTINCT tech_parent.parent) AS array_agg
           FROM tech_parent
          WHERE tech_parent.child = ag.group_id) AS parents,
    ( SELECT array_agg(DISTINCT tech_parent.child) AS array_agg
           FROM tech_parent
          WHERE tech_parent.parent = ag.group_id) AS children,
    kg.tags,
    kg.icon_slugs
   FROM aggregated_groups ag
     LEFT JOIN tech kg ON ag.group_id = kg.id
  GROUP BY ag.group_id, ag.total_count, ag.keywords, kg.category, kg.tags, kg.icon_slugs
  ORDER BY ag.total_count DESC, ag.group_id;

CREATE MATERIALIZED VIEW public."mv_tech_category" AS
 SELECT category,
    count(*) AS count
   FROM tech
  GROUP BY category
  ORDER BY (count(*)) DESC;

CREATE MATERIALIZED VIEW public."mv_tech_combo_stats" AS
 WITH raw_job_salaries AS (
         SELECT kga.tech AS tech1,
            kgb.tech AS tech2,
            COALESCE(kga.label, kga.tech) AS tech1_label,
            COALESCE(kgb.label, kgb.tech) AS tech2_label,
            kga.category AS cat1,
            kgb.category AS cat2,
            kga.tags AS tech1_tags,
            kgb.tags AS tech2_tags,
            kga.icon_slugs AS tech1_icons,
            kgb.icon_slugs AS tech2_icons,
            j.id AS job_id,
                CASE
                    WHEN j.salary_type = 'month'::text AND j.min_salary > 0 AND j.max_salary < 9999999 THEN j.min_salary
                    ELSE NULL::integer
                END::double precision AS min_month,
                CASE
                    WHEN j.salary_type = 'month'::text AND j.min_salary > 0 AND j.max_salary < 9999999 THEN j.max_salary
                    ELSE NULL::integer
                END::double precision AS max_month,
                CASE
                    WHEN j.salary_type = 'year'::text AND j.min_salary > 0 AND j.max_salary < 9999999 THEN j.min_salary
                    ELSE NULL::integer
                END::double precision AS min_year,
                CASE
                    WHEN j.salary_type = 'year'::text AND j.min_salary > 0 AND j.max_salary < 9999999 THEN j.max_salary
                    ELSE NULL::integer
                END::double precision AS max_year
           FROM job_tech a
             JOIN job_tech b ON a.job_id = b.job_id
             JOIN job j ON j.id = a.job_id
             JOIN mv_tech kga ON kga.tech = a.tech
             JOIN mv_tech kgb ON kgb.tech = b.tech
          WHERE 1 = 1 AND kgb.parents @> ARRAY[kga.tech]
        ), median_stats AS (
         SELECT raw_job_salaries.tech1,
            raw_job_salaries.tech2,
            raw_job_salaries.tech1_label,
            raw_job_salaries.tech2_label,
            raw_job_salaries.cat1,
            raw_job_salaries.cat2,
            raw_job_salaries.tech1_tags,
            raw_job_salaries.tech2_tags,
            raw_job_salaries.tech1_icons,
            raw_job_salaries.tech2_icons,
            count(DISTINCT raw_job_salaries.job_id) AS job_count,
            percentile_cont(0.5::double precision) WITHIN GROUP (ORDER BY raw_job_salaries.min_month) AS median_min_month,
            percentile_cont(0.5::double precision) WITHIN GROUP (ORDER BY raw_job_salaries.max_month) AS median_max_month,
            percentile_cont(0.5::double precision) WITHIN GROUP (ORDER BY raw_job_salaries.min_year) AS median_min_year,
            percentile_cont(0.5::double precision) WITHIN GROUP (ORDER BY raw_job_salaries.max_year) AS median_max_year,
            percentile_cont(0.75::double precision) WITHIN GROUP (ORDER BY raw_job_salaries.min_month) AS pr75_min_month,
            percentile_cont(0.75::double precision) WITHIN GROUP (ORDER BY raw_job_salaries.max_month) AS pr75_max_month,
            percentile_cont(0.75::double precision) WITHIN GROUP (ORDER BY raw_job_salaries.min_year) AS pr75_min_year,
            percentile_cont(0.75::double precision) WITHIN GROUP (ORDER BY raw_job_salaries.max_year) AS pr75_max_year,
            percentile_cont(0.88::double precision) WITHIN GROUP (ORDER BY raw_job_salaries.min_month) AS pr88_min_month,
            percentile_cont(0.88::double precision) WITHIN GROUP (ORDER BY raw_job_salaries.max_month) AS pr88_max_month,
            percentile_cont(0.88::double precision) WITHIN GROUP (ORDER BY raw_job_salaries.min_year) AS pr88_min_year,
            percentile_cont(0.88::double precision) WITHIN GROUP (ORDER BY raw_job_salaries.max_year) AS pr88_max_year
           FROM raw_job_salaries
          GROUP BY raw_job_salaries.tech1, raw_job_salaries.tech2, raw_job_salaries.tech1_label, raw_job_salaries.tech2_label, raw_job_salaries.cat1, raw_job_salaries.cat2, raw_job_salaries.tech1_tags, raw_job_salaries.tech2_tags, raw_job_salaries.tech1_icons, raw_job_salaries.tech2_icons
         HAVING count(DISTINCT raw_job_salaries.job_id) >= 2
        )
 SELECT tech1,
    tech2,
    tech1_label,
    tech2_label,
    cat1,
    cat2,
    tech1_tags,
    tech2_tags,
    tech1_icons,
    tech2_icons,
    job_count,
    round(median_min_month::numeric) AS median_min_month,
    round(median_max_month::numeric) AS median_max_month,
    round(median_min_year::numeric) AS median_min_year,
    round(median_max_year::numeric) AS median_max_year,
    round(pr75_min_month::numeric) AS pr75_min_month,
    round(pr75_max_month::numeric) AS pr75_max_month,
    round(pr75_min_year::numeric) AS pr75_min_year,
    round(pr75_max_year::numeric) AS pr75_max_year,
    round(pr88_min_month::numeric) AS pr88_min_month,
    round(pr88_max_month::numeric) AS pr88_max_month,
    round(pr88_min_year::numeric) AS pr88_min_year,
    round(pr88_max_year::numeric) AS pr88_max_year,
    round((median_min_month + median_max_month)::numeric / 2::numeric, 0) AS month_median_avg,
    round((median_min_year + median_max_year)::numeric / 2::numeric, 0) AS year_median_avg,
    round((pr75_min_month + pr75_max_month)::numeric / 2::numeric, 0) AS month_pr75_avg,
    round((pr75_min_year + pr75_max_year)::numeric / 2::numeric, 0) AS year_pr75_avg,
    round((pr88_min_month + pr88_max_month)::numeric / 2::numeric, 0) AS month_pr88_avg,
    round((pr88_min_year + pr88_max_year)::numeric / 2::numeric, 0) AS year_pr88_avg
   FROM median_stats;

CREATE MATERIALIZED VIEW public."mv_tech_ranking" AS
 WITH raw_job_salaries AS (
         SELECT jjkg.tech AS keyword_group,
            kg.category,
            kg.label,
            kg.tags,
            kg.icon_slugs,
            j.id AS job_id,
                CASE
                    WHEN j.salary_type = 'month'::text AND j.min_salary > 0 AND j.max_salary < 9999999 THEN j.min_salary
                    ELSE NULL::integer
                END::double precision AS min_month,
                CASE
                    WHEN j.salary_type = 'month'::text AND j.min_salary > 0 AND j.max_salary < 9999999 THEN j.max_salary
                    ELSE NULL::integer
                END::double precision AS max_month,
                CASE
                    WHEN j.salary_type = 'year'::text AND j.min_salary > 0 AND j.max_salary < 9999999 THEN j.min_salary
                    ELSE NULL::integer
                END::double precision AS min_year,
                CASE
                    WHEN j.salary_type = 'year'::text AND j.min_salary > 0 AND j.max_salary < 9999999 THEN j.max_salary
                    ELSE NULL::integer
                END::double precision AS max_year
           FROM job_tech jjkg
             JOIN job j ON j.id = jjkg.job_id
             JOIN tech kg ON kg.id = jjkg.tech
        ), median_stats AS (
         SELECT raw_job_salaries.keyword_group,
            raw_job_salaries.category,
            raw_job_salaries.label,
            raw_job_salaries.tags,
            raw_job_salaries.icon_slugs,
            count(DISTINCT raw_job_salaries.job_id) AS job_count,
            percentile_cont(0.5::double precision) WITHIN GROUP (ORDER BY raw_job_salaries.min_month) AS median_min_month,
            percentile_cont(0.5::double precision) WITHIN GROUP (ORDER BY raw_job_salaries.max_month) AS median_max_month,
            percentile_cont(0.5::double precision) WITHIN GROUP (ORDER BY raw_job_salaries.min_year) AS median_min_year,
            percentile_cont(0.5::double precision) WITHIN GROUP (ORDER BY raw_job_salaries.max_year) AS median_max_year,
            percentile_cont(0.75::double precision) WITHIN GROUP (ORDER BY raw_job_salaries.min_month) AS pr75_min_month,
            percentile_cont(0.75::double precision) WITHIN GROUP (ORDER BY raw_job_salaries.max_month) AS pr75_max_month,
            percentile_cont(0.75::double precision) WITHIN GROUP (ORDER BY raw_job_salaries.min_year) AS pr75_min_year,
            percentile_cont(0.75::double precision) WITHIN GROUP (ORDER BY raw_job_salaries.max_year) AS pr75_max_year,
            percentile_cont(0.88::double precision) WITHIN GROUP (ORDER BY raw_job_salaries.min_month) AS pr88_min_month,
            percentile_cont(0.88::double precision) WITHIN GROUP (ORDER BY raw_job_salaries.max_month) AS pr88_max_month,
            percentile_cont(0.88::double precision) WITHIN GROUP (ORDER BY raw_job_salaries.min_year) AS pr88_min_year,
            percentile_cont(0.88::double precision) WITHIN GROUP (ORDER BY raw_job_salaries.max_year) AS pr88_max_year
           FROM raw_job_salaries
          GROUP BY raw_job_salaries.keyword_group, raw_job_salaries.category, raw_job_salaries.label, raw_job_salaries.tags, raw_job_salaries.icon_slugs
         HAVING count(DISTINCT raw_job_salaries.job_id) >= 2
        )
 SELECT keyword_group AS tech,
    category,
    label,
    tags,
    icon_slugs,
    job_count,
    round((median_min_month + median_max_month)::numeric / 2::numeric, 0) AS month_median_avg,
    round((median_min_year + median_max_year)::numeric / 2::numeric, 0) AS year_median_avg,
    round((pr75_min_month + pr75_max_month)::numeric / 2::numeric, 0) AS month_pr75_avg,
    round((pr75_min_year + pr75_max_year)::numeric / 2::numeric, 0) AS year_pr75_avg,
    round((pr88_min_month + pr88_max_month)::numeric / 2::numeric, 0) AS month_pr88_avg,
    round((pr88_min_year + pr88_max_year)::numeric / 2::numeric, 0) AS year_pr88_avg
   FROM median_stats;

CREATE MATERIALIZED VIEW public."mv_tech_tags" AS
 WITH flattened_tags AS (
         SELECT tech.id AS keyword_group_id,
            tech.category,
            unnest(tech.tags) AS tag
           FROM tech
          WHERE tech.tags IS NOT NULL
        )
 SELECT tag,
    category,
    count(*) AS count
   FROM flattened_tags
  GROUP BY tag, category;

-- ============ Functions ============
CREATE OR REPLACE FUNCTION public.get_job_count()
 RETURNS TABLE(month_salary_type_jobs bigint, year_salary_type_jobs bigint, open_jobs bigint, jobs bigint)
 LANGUAGE sql
AS $function$
  SELECT
    COUNT(*) FILTER (
      WHERE max_salary <> 9999999 AND min_salary <> 0 AND salary_type = 'month' AND closed = false
    ) AS month_salary_type_jobs,
    
    COUNT(*) FILTER (
      WHERE max_salary <> 9999999 AND min_salary <> 0 AND salary_type = 'year' AND closed = false
    ) AS year_salary_type_jobs,
    
    COUNT(*) FILTER (
      WHERE closed = false
    ) AS open_jobs,
    
    COUNT(*) AS jobs
  FROM
    job;
$function$;

CREATE OR REPLACE FUNCTION public.get_job_crawl_stats(p_days integer DEFAULT 7)
 RETURNS TABLE(new_jobs_date date, new_jobs_count bigint, updated_jobs_date date, updated_jobs_count bigint)
 LANGUAGE sql
 STABLE
AS $function$
  WITH bounds AS (
    SELECT
      max(created_at)::date AS c_date,
      max(updated_at)::date AS u_date
    FROM job
  )
  SELECT
    b.c_date AS new_jobs_date,
    (SELECT count(*) FROM job WHERE created_at::date >= b.c_date - p_days) AS new_jobs_count,
    b.u_date AS updated_jobs_date,
    (SELECT count(*) FROM job WHERE updated_at::date >= b.u_date - p_days) AS updated_jobs_count
  FROM bounds b;
$function$;

CREATE OR REPLACE FUNCTION public.get_job_preference_count(p_user_id uuid)
 RETURNS json
 LANGUAGE sql
 STABLE SECURITY DEFINER
AS $function$select
  json_build_object(
    'liked_count',
    COUNT(*) filter (
      where
        preference = 'like'
    ),
    'disliked_count',
    COUNT(*) filter (
      where
        preference = 'dislike'
    )
  )
from
  job_preference jp
  left join job j on j.id = jp.job_id
where
  user_id = p_user_id and j.closed = false$function$;

CREATE OR REPLACE FUNCTION public.get_job_update_date_counts()
 RETURNS TABLE(updated_date date, count bigint)
 LANGUAGE sql
 STABLE
AS $function$
  SELECT updated_at::date AS updated_date, count(*) AS count
  FROM job
  GROUP BY updated_at::date
  ORDER BY updated_at::date DESC;
$function$;

CREATE OR REPLACE FUNCTION public.get_jobs_by_preference(p_user_id uuid, p_preference text)
 RETURNS TABLE(id text, title text, location text, detail_link text, salary text, salary_type text, min_salary integer, max_salary integer, avg_salary numeric, created_at timestamp with time zone, updated_at timestamp with time zone, description text, company_id text, company_name text, company_link text, company_type text, techs text[], tech_mappings text[], closed boolean, description_ch_en_ratio numeric, preference_updated_at timestamp with time zone)
 LANGUAGE sql
 STABLE
AS $function$
  SELECT j.*, jp.updated_at AS preference_updated_at
  FROM mv_job j
  JOIN job_preference jp
    ON jp.job_id = j.id
   AND jp.user_id = p_user_id
   AND jp.preference = p_preference;
$function$;

CREATE OR REPLACE FUNCTION public.get_location_anomaly_jobs(p_type text, p_maxlen integer DEFAULT 30)
 RETURNS SETOF job
 LANGUAGE sql
 STABLE
AS $function$
  SELECT j.*
  FROM job j
  WHERE j.closed = false
    AND CASE p_type
      WHEN 'blank' THEN (j.location IS NULL OR btrim(j.location) = '')
      WHEN 'unmapped' THEN NOT EXISTS (
        SELECT 1 FROM location_group_location lgl
        WHERE lgl.location = j.location
      )
      WHEN 'malformed' THEN char_length(btrim(coalesce(j.location, ''))) > p_maxlen
      ELSE false
    END;
$function$;

CREATE OR REPLACE FUNCTION public.get_tech_combo_stats(p_limit integer DEFAULT 15)
 RETURNS TABLE(tech1 text, tech2 text, tech1_label text, tech2_label text, cat1 text, cat2 text, job_count bigint, avg_min_month numeric, avg_max_month numeric, avg_min_year numeric, avg_max_year numeric)
 LANGUAGE sql
 STABLE SECURITY DEFINER
AS $function$SELECT tech1, tech2, tech1_label, tech2_label, cat1, cat2, job_count,
         avg_min_month, avg_max_month, avg_min_year, avg_max_year
  FROM public.mv_tech_combo_stats
  ORDER BY job_count DESC
  LIMIT p_limit;$function$;

CREATE OR REPLACE FUNCTION public.get_unreviewed_jobs(p_user_id uuid)
 RETURNS SETOF mv_job
 LANGUAGE sql
 STABLE
AS $function$
   SELECT j.*
   FROM mv_job j
   WHERE NOT EXISTS (
     SELECT 1 FROM job_preference jp
     WHERE jp.job_id = j.id
       AND jp.user_id = p_user_id
   );
 $function$;

CREATE OR REPLACE FUNCTION public.get_weighted_market_ratio()
 RETURNS TABLE(weighted_market_ratio numeric, total_valid_samples bigint)
 LANGUAGE sql
AS $function$
  WITH ratio_counts as (
    select
      ROUND(CAST(max_salary as NUMERIC) / min_salary, 2) as ratio,
      COUNT(*) as group_count
    from
      job
    where
      min_salary > 0
      and max_salary < 9999999 -- 排除「以上」和「面議」
      and max_salary >= min_salary
    group by
      1
    order by group_count desc
  )
  select
    -- 公式：SUM(比例 * 該比例的人數) / 總人數
    ROUND(SUM(ratio * group_count) / SUM(group_count), 2) as weighted_market_ratio,
    SUM(group_count) as total_valid_samples
  from
    ratio_counts;
$function$;

CREATE OR REPLACE FUNCTION public.refresh_mv_company()
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  REFRESH MATERIALIZED VIEW CONCURRENTLY public.mv_company;
END;
$function$;

CREATE OR REPLACE FUNCTION public.refresh_mv_job()
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  REFRESH MATERIALIZED VIEW CONCURRENTLY public.mv_job;
END;
$function$;

CREATE OR REPLACE FUNCTION public.refresh_mv_location_group()
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
begin
  refresh materialized view concurrently public.mv_location_group;
end;
$function$;

CREATE OR REPLACE FUNCTION public.refresh_mv_salary_type_median_ratio()
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  REFRESH MATERIALIZED VIEW CONCURRENTLY public.mv_salary_type_median_ratio;
END;
$function$;

CREATE OR REPLACE FUNCTION public.refresh_mv_salary_weighted_ratio()
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  REFRESH MATERIALIZED VIEW CONCURRENTLY public.mv_salary_weighted_ratio;
END;
$function$;

CREATE OR REPLACE FUNCTION public.refresh_mv_tech()
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  REFRESH MATERIALIZED VIEW CONCURRENTLY public.mv_tech;
END;
$function$;

CREATE OR REPLACE FUNCTION public.refresh_mv_tech_category()
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  REFRESH MATERIALIZED VIEW CONCURRENTLY public.mv_tech_category;
END;
$function$;

CREATE OR REPLACE FUNCTION public.refresh_mv_tech_combo_stats()
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  REFRESH MATERIALIZED VIEW CONCURRENTLY public.mv_tech_combo_stats;
END;
$function$;

CREATE OR REPLACE FUNCTION public.refresh_mv_tech_ranking()
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  REFRESH MATERIALIZED VIEW CONCURRENTLY public.mv_tech_ranking;
END;
$function$;

CREATE OR REPLACE FUNCTION public.refresh_mv_tech_tags()
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  REFRESH MATERIALIZED VIEW CONCURRENTLY public.mv_tech_tags;
END;
$function$;

CREATE OR REPLACE FUNCTION public.reset_keywords()
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$BEGIN
  ALTER TABLE tech_keyword
    DROP CONSTRAINT IF EXISTS tech_keyword_mapping_keyword_fkey;

  TRUNCATE TABLE keyword;

  INSERT INTO keyword (id, count)
  SELECT kw, COUNT(*) AS count
  FROM job_keyword, UNNEST(keywords) AS kw
  GROUP BY kw

  UNION ALL

  SELECT k.keyword, 1
  FROM tech_keyword k
  WHERE k.keyword NOT IN (
    SELECT DISTINCT kw
    FROM job_keyword, UNNEST(keywords) AS kw
  );

  ALTER TABLE tech_keyword
    ADD CONSTRAINT tech_keyword_mapping_keyword_fkey
    FOREIGN KEY (keyword) REFERENCES keyword(id);
END;$function$;
