allowBuilds:
  '@nestjs/core': true
  '@openrouter/sdk': true
  '@parcel/watcher': true
  '@scarf/scarf': true
  '@swc/core': true
  core-js-pure: true
  esbuild: true
  nx: true
  puppeteer: true
  rebrowser-puppeteer: true
  unrs-resolver: true

ignoredBuiltDependencies:
  - '@openrouter/sdk'

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@scarf/scarf'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - core-js
  - core-js-pure
  - esbuild
  - msw
  - nx
  - oxc-resolver
  - puppeteer
  - rebrowser-puppeteer
  - supabase
  - unrs-resolver
  - vue-demi
