ignoredBuiltDependencies:
  - '@openrouter/sdk'

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@scarf/scarf'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - core-js
  - core-js-pure
  - esbuild
  - msw
  - nx
  - oxc-resolver
  - puppeteer
  - rebrowser-puppeteer
  - supabase
  - unrs-resolver
  - vue-demi
