-- Splits `job.updated_at` into two separate columns: `crawled_at` (last time
-- the crawler processed this job, regardless of whether content changed) and
-- a new `updated_at` (last time the job's content actually changed). Today
-- `updated_at` is bumped on every re-crawl even when nothing changed, which
-- makes the "updated" timestamp shown to job seekers meaningless and makes
-- it impossible for ops to tell whether a job's content really changed.
--
-- Requirement 1.1: Job 資料 shall 提供獨立的「爬取時間」欄位。
-- Requirement 1.2: Job 資料 shall 提供獨立的「異動時間」欄位。
-- Requirement 1.3: 既有資料遷移時，「爬取時間」初始值設為遷移前的 updated_at。
-- Requirement 1.4: 既有資料遷移時，「異動時間」初始值與「爬取時間」相同（逐列對應，
--   而非整表填入單一時間值）。
--
-- Source of truth for this DDL:
-- .kiro/specs/job-timestamp-separation/design.md
--   -> "6.1 Job Schema Migration" (steps 1-6, covering tasks 1.1-1.2)
-- .kiro/specs/job-timestamp-separation/research.md
--   -> "設計階段補充" -> "一次性 backfill 的正確寫法"
--   -> "設計階段補充" -> "對第 1 節「mv_job 零改動」結論的修正"
--
-- IMPORTANT: `ADD COLUMN ... DEFAULT now()` cannot be used here. `now()` is
-- volatile, so Postgres cannot take the metadata-only fast path and would
-- rewrite the whole table, giving every existing row the *same* ALTER-TABLE-
-- time value instead of each row's own prior `updated_at` value. That would
-- violate Requirement 1.4. Instead: add the column with no default, backfill
-- it row-by-row from `crawled_at`, set NOT NULL, and only then attach a
-- default for future inserts.
--
-- Note: this migration continues in the same file with the crawl-stats
-- function updates (`get_job_crawl_stats`/`get_job_update_date_counts`,
-- task 1.3), appended after the mv_job rebuild below (task 1.2).

-- Step 1: rename existing `updated_at` (crawl time) to `crawled_at`.
ALTER TABLE public."job" RENAME COLUMN "updated_at" TO "crawled_at";

-- Step 2: add the new `updated_at` (real content-change time) column
-- without a volatile default, so backfill below can set each row's own
-- value instead of every row getting the same ALTER-TABLE-time value.
ALTER TABLE public."job" ADD COLUMN "updated_at" timestamp with time zone;

-- Step 3: backfill every existing row's `updated_at` with its own
-- `crawled_at` value (row-by-row correlated assignment, not a literal).
UPDATE public."job" SET "updated_at" = "crawled_at";

-- Step 4: now that every row has a value, enforce NOT NULL.
ALTER TABLE public."job" ALTER COLUMN "updated_at" SET NOT NULL;

-- Step 5: attach a default for future inserts only (applied after backfill
-- and NOT NULL so it cannot affect the backfill above).
ALTER TABLE public."job" ALTER COLUMN "updated_at" SET DEFAULT (now() AT TIME ZONE 'utc');

-- Step 6: rebuild `mv_job` so it is redefined against the current column
-- set, at a point in this migration where `j.updated_at` now resolves to
-- the true-change-time column added in Step 2, not the crawl-time column
-- renamed to `crawled_at` in Step 1.
--
-- WHY DROP + CREATE (not left alone): `ALTER TABLE ... RENAME COLUMN`
-- (Step 1) only keeps mv_job's *internal*, attnum-based reference pointing
-- at the same underlying physical column -- it does not retarget mv_job to
-- the newly added `updated_at` column, and mv_job's own exposed attribute
-- names/definition are frozen at `CREATE MATERIALIZED VIEW` time. Left
-- untouched, `mv_job.updated_at` would keep silently resolving to the
-- renamed `crawled_at` physical column forever (no error, wrong data),
-- contradicting Requirement 3.2. Postgres materialized views do not
-- support `CREATE OR REPLACE`, so this must be an explicit DROP + CREATE.
-- See research.md "設計階段補充 -> 對第 1 節「mv_job 零改動」結論的修正".
--
-- WHY THIS SELECT LIST INCLUDES `keyword_groups` EVEN THOUGH
-- `supabase/schema.sql`'S CURRENT mv_job TEXT DOES NOT: schema.sql is a
-- manually regenerated snapshot (its own header says "Generated by
-- scripts/sync-supabase-schema.mjs on 2026-07-17T11:14:10"), and
-- `mcp__Supabase__list_migrations` against this project's live database
-- confirms the last *applied* migration is
-- `alter_refresh_mv_job_statement_timeout` (20260717...). Migrations
-- 20260714000000/010000/020000 -- which add `job_keyword.keyword_groups`
-- and thread it through `mv_job` / `get_unreviewed_jobs` /
-- `get_jobs_by_preference` -- are committed to this repo but NOT YET
-- applied, exactly like this file. Supabase applies pending migrations in
-- ascending filename-timestamp order, so
-- `20260714020000_alter_mv_job_add_keyword_groups.sql` will run before
-- this file the next time migrations are pushed. By the time THIS
-- DROP/CREATE executes, the real `mv_job` it is replacing already has
-- `keyword_groups`. Recreating from the stale schema.sql text (omitting
-- `keyword_groups`) would silently drop that column and break
-- `get_jobs_by_preference`, which that same prior migration already
-- widened to a `RETURNS TABLE(...)` expecting a `keyword_groups jsonb`
-- column out of `j.*`. This block instead mirrors
-- `20260714020000_alter_mv_job_add_keyword_groups.sql`'s SELECT list
-- exactly, with only the `updated_at` binding naturally changed by Steps
-- 1-5 above.
--
-- `get_unreviewed_jobs()` is declared `RETURNS SETOF mv_job`, a hard
-- dependency on mv_job's composite row type (unlike the other functions
-- below, which only reference `mv_job` by name inside opaque SQL body
-- text -- not a blocking dependency for traditional-syntax SQL functions).
-- A plain `DROP MATERIALIZED VIEW mv_job;` would fail with "cannot drop
-- ... because other objects depend on it" unless this function is dropped
-- first (chosen here, over `DROP ... CASCADE`, to keep the drop targeted
-- rather than silently removing dependents we may not have fully
-- enumerated). Its body is unchanged -- recreated as-is afterward,
-- matching `20260714020000_alter_mv_job_add_keyword_groups.sql`.
DROP FUNCTION IF EXISTS public.get_unreviewed_jobs(uuid);
DROP MATERIALIZED VIEW IF EXISTS public.mv_job;

CREATE MATERIALIZED VIEW public."mv_job" AS
 SELECT j.id,
    j.title,
    COALESCE(lg.id, j.location) AS location,
    j.detail_link,
    j.salary,
    j.salary_type,
    j.min_salary,
    j.max_salary,
        CASE
            WHEN j.min_salary > 0 AND j.max_salary < 9999999 THEN round((j.min_salary + j.max_salary)::numeric / 2.0, 0)
            WHEN j.min_salary > 0 AND j.max_salary = 9999999 THEN round(j.min_salary::numeric * (1.0 + mv.ratio) / 2.0, 0)
            ELSE NULL::numeric
        END AS avg_salary,
    j.created_at,
    j.updated_at,
    j.description,
    c.id AS company_id,
    c.name AS company_name,
    c.link AS company_link,
    c.type AS company_type,
    array_agg(jkg.tech) FILTER (WHERE jkg.tech IS NOT NULL) AS techs,
    array_agg((jkg.tech || ':'::text) || jkg.keywords) FILTER (WHERE jkg.tech IS NOT NULL) AS tech_mappings,
    j.closed,
    jk.description_ch_en_ratio,
    jk.keyword_groups
   FROM job j
     JOIN job_keyword jk ON jk.id = j.id
     JOIN company c ON j.company_id = c.id
     LEFT JOIN job_tech jkg ON jkg.job_id = j.id
     LEFT JOIN location_group_location lgl ON j.location = lgl.location
     LEFT JOIN location_group lg ON lgl.location_group = lg.id
     LEFT JOIN mv_salary_range_multiplier mv ON j.salary_type = mv.salary_type
  WHERE j.closed = false
  GROUP BY j.id, j.title, (COALESCE(lg.id, j.location)), j.detail_link, j.salary, j.salary_type, j.min_salary, j.max_salary, j.created_at, j.updated_at, j.description, c.id, c.name, c.link, c.type, jk.description_ch_en_ratio, j.closed, mv.ratio, jk.keyword_groups
  ORDER BY j.min_salary DESC, j.max_salary DESC, j.updated_at DESC;

-- Step 7: recreate the 8 indexes that exist on mv_job today -- the 7 listed
-- in design.md's §6.1 step 6 plus `mv_job_location_idx`, which that
-- inventory omitted but which is present both in schema.sql and in
-- `20260714020000_alter_mv_job_add_keyword_groups.sql` (see CONCERNS in
-- the status report). `mv_job_id_idx` (UNIQUE) is required for
-- `refresh_mv_job()`'s `REFRESH MATERIALIZED VIEW CONCURRENTLY` to keep
-- working.
CREATE UNIQUE INDEX mv_job_id_idx ON public.mv_job USING btree (id);
CREATE INDEX ix_mv_job_company_id ON public.mv_job USING btree (company_id);
CREATE INDEX ix_mv_job_max_salary ON public.mv_job USING btree (max_salary DESC);
CREATE INDEX ix_mv_job_min_salary ON public.mv_job USING btree (min_salary DESC);
CREATE INDEX ix_mv_job_salary_type ON public.mv_job USING btree (salary_type);
CREATE INDEX ix_mv_job_techs ON public.mv_job USING gin (techs);
CREATE INDEX ix_mv_job_updated_at ON public.mv_job USING btree (updated_at DESC);
CREATE INDEX mv_job_location_idx ON public.mv_job USING btree (location);

-- Step 8: recreate `get_unreviewed_jobs()`, dropped above only as a side
-- effect of removing its hard dependency on the old mv_job composite type.
-- Body is unchanged -- it does not reference `updated_at`/`crawled_at`
-- directly, so no logic change is needed here.
CREATE OR REPLACE FUNCTION public.get_unreviewed_jobs(p_user_id uuid)
 RETURNS SETOF mv_job
 LANGUAGE sql
 STABLE
AS $function$
   SELECT j.*
   FROM mv_job j
   WHERE NOT EXISTS (
     SELECT 1 FROM job_preference jp
     WHERE jp.job_id = j.id
       AND jp.user_id = p_user_id
   );
 $function$;
